### ISSUE TITLE
黑暗主题下，说明文字没有可见性

### ISSUE THREAD

**Issue by antnesswcm** [AnmSleepalone/setfnlock#1]
![image](https://github.com/user-attachments/assets/b2f02a44-f756-4ed4-85ea-98eba9d4f4b1)
win10系统，系统为暗色模式，软件在暗色模式下，说明文字没有可见性，此外"打开"、"关闭"文字没有对齐，希望作者有时间可以改进一下，谢谢!

=======

大爱作者，解决了大问题，代码也有参考意义!!

**Comment by AnmSleepalone** [comment]
不好意思,最近都没有看GITHUB,已经适配了深色模式,修改了界面
