### ISSUE TITLE
macos下如何运行

### ISSUE THREAD

**Issue by vectorstone** [AnmSleepalone/setfnlock#4]
请问下,macos下如何运行

**Comment by AnmSleepalone** [comment]
请在releases中下载[setFn.app.tar.gz]，
解压后可以得到app，可能会提示不能运行，搜索引擎有相关解决办法，如果还不能运行可以告知我，我手头现在没有macos的机器

> (https://github.com/AnmSleepalone/setfnlock/releases/download/v0.2.5/setFn.app.tar.gz)

**Comment by 29789** [comment]
![CleanShot 2024-12-17 at 15 37 39@2x](https://github.com/user-attachments/assets/ad496e5a-c5df-4e6c-a84d-ddd8fd078b1a)
m1芯片的 mac 运行不了

**Comment by AnmSleepalone** [comment]
> ![CleanShot 2024-12-17 at 15 37 39@2x](https://private-user-images.githubusercontent.com/40969647/396399142-ad496e5a-c5df-4e6c-a84d-ddd8fd078b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODQ1MDQsIm5iZiI6MTczNDQ4NDIwNCwicGF0aCI6Ii80MDk2OTY0Ny8zOTYzOTkxNDItYWQ0OTZlNWEtYzVkZi00ZTZjLWE4NGQtZGRkOGZkMDc4YjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxMTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOTg2MDZiM2Q3OTgxZDM4NjAzYThhOGUxNTgyZmZmNzA3NTVhOTgyOGM4OTEzYzA4ZDY5ZTY2MTVlZjg2MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L1OACG7xfLBQafxs8wFPxVNgwUukMZENv9qZOWerwNg) m1芯片的 mac 运行不了

不支持M系列芯片

**Comment by vectorstone** [comment]
可以参考这个帖子,m系列的芯片也支持
https://wswxgpp.eu.org/2024/12/29/%E7%BD%97%E6%8A%80k380%E9%94%AE%E7%9B%98%E5%88%87%E6%8D%A2%E9%BB%98%E8%AE%A4%E5%8A%9F%E8%83%BD%E9%94%AE/

**Comment by 29789** [comment]
感谢🙏，我试试
